[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.7.7", features = ["csr"] }
leptos_meta = { version = "0.7.7" }
leptos_transition_group = { path = "../../" }
thaw = { version = "0.4.3", features = ["csr"] }